### ISSUE TITLE
Superstarv2 Unit Tests

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#100]

**Comment by mrmoss** [comment]
It's probably better for someone other than me to do these...but I can at least start them out...

**Comment by Arsh25** [comment]
This is something I could do. [Catch](https://github.com/philsquared/Catch) is something easy to use unless you want to roll your own system. 

Going to assign myself too

**Comment by mrmoss** [comment]
I've always found using Catch for any actual test bed rather difficult to use. It makes adding tests easy...but it makes debugging and reading why tests fail difficult...which is the opposite way of every testing lecture I've been to.

I think this is literally a vector of a test struct that has the thing you want to test in it and what it is expected to output (since everything is a get/set).

I'd also like to add in a separate timing analysis testing program.

Right now there's a blank unit_tests.cpp that's been in there since the beginning of development...I'll start adding in some simple test cases.

The majority of the help I'm seeking is more test cases rather then writing the code for them. I think I've got the majority of the "weird requests" and technicalities of using arrays/objects as a path...but I'm not sure.

**Comment by mrmoss** [comment]
I wanna say this is done yes?
