### ISSUE TITLE
Superstarv2 migration.

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#104]
As soon as testing and such is done, we need to migrate over to the new version (assuming we still want it), mainly since it isn't a "drop-in" change over since the new backend has a very different system...transferring old databases and such might be tricky.

**Comment by Arsh25** [comment]
For DB transfer I'm thinking we could use Ben's expand utility and parse the directories produced into a the new format or create a utility that copies an old robot into the new format. In either we would need a new utility.

**Comment by mrmoss** [comment]
I'm planning to make the old database format loadable by the new
version...but I'd like to start storing the database as a JSON object (so
just rewrite the database as a JSON object from then on).  This is issue is
more or less just a formality...I actually think the migration will be
pretty simple.

**Comment by mrmoss** [comment]
Just moved test.robotmoose.com to superstarv2, please take a look and see what's broken.

**Comment by mrmoss** [comment]
All backends are broken...

**Comment by Michaeasmith** [comment]
Two things I just noticed from home: 

Did a git pull, ran local superstar, and the page gives an error when I click on "Robots": 
VM1626:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
xmlhttp.onreadystatechange @ superstar.js:149

Secondly, on test.robotmoose it looks like simulations are no longer supported with the new config_editor.js, robot_network.js, and maybe other files, but I can fix that.

**Comment by mrmoss** [comment]
I'm actually going to revert to the old version...I don't want to leave this broken...

**Comment by mrmoss** [comment]
I'm guessing your error was a caching/old version issue (new superstar expects JSON), were you running superstarv2?

I moved this to a new branch: superstarv2_migration

**Comment by Michaeasmith** [comment]
Oh, nope, I was running the old superstar. I tried running it before even looking at the files, and I had assumed you had just replaced superstar.cpp. I'll play around with the new branch.
