### ISSUE TITLE
Frontend simulation testing

### ISSUE THREAD

**Issue by Michaeasmith** [robotmoose/robotmoose#106]
I finished the frontend simulator, but it would be nice if someone could test it and take a look at the code, to make sure it is working well and I didn't break anything else in the frontend.

The frontend simulator stores the experiments, configuration, and gui data in localStorage. For a create2, it simulates movement using the same code as the robot_2wd simulator we used for the arduino code simulations.

By the way, what is the right procedure here for committing something to close an issue when the commit needs testing? Is it right to close the issue and make a new issue for testing, as I did here, or is it better to leave the issue open and request testing in the comments?

**Comment by Arsh25** [comment]
This is a good question. I think the cleanest way to do it would be using
Milestones https://guides.github.com/features/issues/#filtering. My
proposed workflow:
1. Work on an issue
2. Test it, commit to repo and close the issue
3. Assign the "Testing" Milestone
4. People looking to test can search by this Milestone, test stuff and
   comment on the issue they are testing.

This is something that should definitely be standardized and worth talking
about on Friday.

**Comment by mrmoss** [comment]
@Michaeasmith You want to test this again? It seems to work for me...but you may know some edge cases I'm not thinking of...

**Comment by Michaeasmith** [comment]
It's working for you? On test.robotmoose when running a simulation it won't let me select a device on the configure tab.

**Comment by Michaeasmith** [comment]
Just pushed a fix. Simulation seems to be working again for me on test.robotmoose. It would be good if someone else can try it too.

**Comment by mrmoss** [comment]
Caching?! Looks good now.
