### ISSUE TITLE
Superstarv2 Documentation

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#109]

**Comment by mrmoss** [comment]
[First review is up.](https://docs.google.com/document/d/1oGs5zI263Xecrs5HO5Bf2DIXb9hnaWFIOWkNzhQ9jhI/edit?usp=sharing)

Would like feedback: @olawlor @atupek @arcshock @FineTralfazz or others that are interested...

**Comment by mrmoss** [comment]
Added change_auth...

**Comment by FineTralfazz** [comment]
I was able to write all of the test scripts using this documentation, without looking at the code at all. So as far as I'm concerned, it's good.

**Comment by computations** [comment]
Would it be possible to include some plain text version of this in the repo? Just so that new devs don't have to go digging through closed tickets to find it.
