### ISSUE TITLE
Map resize.

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#117]
It would be nice if the map resized to the size of the doorway. It does do this up initial creation, but not when the doorway is resized.

This _should_ be easy to implement. As the doorway object has a .onresize and the 3d renderer does have a .width, .height, and a .resize().

**Comment by Michaeasmith** [comment]
Fix pushed to repo. Note: the callback in .resizer was ".onresized", but I changed it to ".onresize". I could not find another place in the repo where this callback was used, so this shouldn't cause problems.
