### ISSUE TITLE
Backend Fullscreen Issues

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#121]
Backend fullscreen button can say "Exit Fullscreen" when you have exited fullscreen via escape button. Should pull this status from the chrome api instead of assuming what it is.

**Comment by mrmoss** [comment]
Would it be easier just to have a button that says fullscreen that doesn't change text/icon?

**Comment by Arsh25** [comment]
Chaging the text is not a big deal and it is sort of nice to have a button that says exit when you're already in fullscreen (Makes the purpose very obvious). The main issue is that we should not make assumptions on the state.

**Comment by mrmoss** [comment]
So the email said you took 122 and 124...so I totally did this... I guess I could have looked at the assigned persons...
