### ISSUE TITLE
Serial dropdown on backend doesn't auto load serial devices.

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#122]
Was seen today during a walkthrough, serial devices do not seem to update on the backend on Windows (haven't tested on other systems).

**Comment by mrmoss** [comment]
I think this is actually a dropdown.js issue not a name.js issue...

**Comment by raikaDial** [comment]
If your list of serial devices changes while the serial dropdown element is selected, the dropdown won't refresh until you click on something else.

**Comment by Arsh25** [comment]
Notice same behaviour for all dropdowns (changing SS does not update schools if dropdown is open) this leads me to believe it is a dropdown_t thing. Should we even worrying about it not updating when open?

**Comment by mrmoss** [comment]
Yes, because then you can't ever select anything...

**Comment by mrmoss** [comment]
@Arsh25, so I noticed if you replace the dropdown.js in the app with the one on the site...it works...at least for me...making a softlink...

**Comment by Arsh25** [comment]
I'm not assigned to this so thx

**Comment by mrmoss** [comment]
Oh, I thought you took it?
