### ISSUE TITLE
Main readme update.

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#127]
The main readme is really out of date. Should be shot more torwards chromeapp and using the Arduino IDE (since the Makefile upload is mainly for us).

The two sections in need of major re-writing: Installation and Setup and Configure and Pilot your Robot with the Web Front End.

Might be worth touching up the first section as well...

**Comment by FineTralfazz** [comment]
I made some updates to it. Feedback?

**Comment by mrmoss** [comment]
Looks good to me. Only one small detail, what's the official name for the OS on Macs nowdays?
- OSX?
- OS X?
- Mac OSX?
- Mac OS?
- Mac?

Literally have no idea...

**Comment by FineTralfazz** [comment]
[They renamed it to macOS a few months ago](http://www.theverge.com/2016/6/13/11906214/apple-mac-os-10-announced-features-siri-wwdc-2016). Yes, with a lowercase m. Sigh.

**Comment by mrmoss** [comment]
Then I'd say you can close this.
