### ISSUE TITLE
Per-robot chat room

### ISSUE THREAD

**Issue by olawlor** [robotmoose/robotmoose#13]
To coordinate backend and frontend, having a little chat room visible to everybody would help a lot.

**Comment by Arsh25** [comment]
Gruveo has chat inbuilt. We can just use that

**Comment by Arsh25** [comment]
Is it crazy to use superstar to do this? Send chats to ?chat and just add them to both the frontend and backend

**Comment by Arsh25** [comment]
Looking into stuff that's already built. Disqus looks promising,

**Comment by olawlor** [comment]
Disqus was quite easy to add to NetRun, and allows a separate "room" per robot.  This is all the HTML it took; you identify the thread by an 'url', in our case robotmoose.com/robots/?robot=2016/uaf/bot

```
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = "netrun"; // required: replace example with your forum shortname
    var disqus_url = "https://lawlor.cs.uaf.edu/netrun/run?hw='.$hwnum.'";
    (function() {
        var dsq = document.createElement("script"); dsq.type = "text/javascript"; dsq.async = true;
        dsq.src = "//" + disqus_shortname + ".disqus.com/embed.js";
        (document.getElementsByTagName("head")[0] || document.getElementsByTagName("body")[0]).appendChild(dsq);
    })();
</script>
```

**Comment by Arsh25** [comment]
Looked into Disqus and have a test version on my local system. Big issue is all comments posted as a guest need to be approved.

**Comment by mrmoss** [comment]
https://github.com/mrmoss/pychat

**Comment by Arsh25** [comment]
I like the idea of using Mike's chat system On hold awaiting discussion with or approval from @olawlor

**Comment by mrmoss** [comment]
@Arsh25 I added a push and pop option to superstar, so you can do:
- http://site/superstar/path?push=1234
- http://site/superstar/path?pop=true
- http://site/superstar/path?push=1234&pop=true

Current implementation uses newline delimiters. This way you can do something like:

```
function chat(robot,alias,msg)
{
    superstar_generic(robot,"chat","?get",
        function(data)
        {
            var max_lines=10;
            var uri="?push="+alias+": "+msg;
            if(data.split("\n")>=10)
                uri+="&pop=true";
            superstar_generic(robot,"chat",uri);
        });
}
```

**Comment by mrmoss** [comment]
Only implemented on frontend...

**Comment by mfrancisco1** [comment]
Looks good.  I really like that the messages stay.  Could we add a shortened timestamp to each messages?

**Comment by Arsh25** [comment]
Timestamps are a good idea and can definitely be done. There are two ways we can do this
 `Pilot 11:41AM: msg` or `Pilot 2 Hours ago: msg`. I personally prefer the relative stamp since then we don't have to worry about or clarify timezones.

**Comment by mrmoss** [comment]
Sounds good. Let's swap the current storage of line delimited strings to
line delimited json objects in the format:
{handle:"str",message:"str",time:ms_since_epoch}

**Comment by raikaDial** [comment]
Relative timestamps are pretty easy with Moment.js. You just store your initial timestamp, then periodically update the time displayed in the chat window with the .fromNow() method. 
http://momentjs.com/

**Comment by Arsh25** [comment]
I wouldn't use a JS library for something this simple. The JS `Date` object does everything we need.

**Comment by mrmoss** [comment]
Javascript already makes this easy:
var diff_seconds=((new Date().getTime())-(new Date(json.time)))/1000;

**Comment by raikaDial** [comment]
Moment.js is a wrapper around Date. I just mentioned it because it formats the relative timestamp for you.

**Comment by mrmoss** [comment]
console.log(""+new Data());
Tue Jun 28 2016 13:13:07 GMT-0800 (AKDT)

**Comment by raikaDial** [comment]
Relative timestamp as in "a few seconds ago", "1 hour ago", "1 day ago", etc.

**Comment by mrmoss** [comment]
Oh, that's kind of nice. It's a single file, I'm down.

**Comment by mrmoss** [comment]
Still need on backend...
