### ISSUE TITLE
Superstar client should have strip http function

### ISSUE THREAD

**Issue by raikaDial** [robotmoose/robotmoose#136]
If someone specifies http or https in their superstar url, it should be stripped to avoid double inclusion.

**Comment by mrmoss** [comment]
Doesn't the python and javascript versions already do this?

**Comment by mrmoss** [comment]
The javasceipt version does. The python utils do this as well, but the
actual client does not. Sounds good, the python should be dead simple (move
code from tools to client). Guessing the c++ client doesn't?

**Comment by Arsh25** [comment]
I believe this is for the c++ version.

**Comment by Arsh25** [comment]
C++ client does not do this

**Comment by mrmoss** [comment]
Crap, you were assigned to this Ryker? How I never see that?

**Comment by raikaDial** [comment]
Yeah, this is just to remind me to do this :)

**Comment by mrmoss** [comment]
It does now...I've got to check assigners better.
