### ISSUE TITLE
dev site not updated

### ISSUE THREAD

**Issue by Michaeasmith** [robotmoose/robotmoose#142]
This probably does not need its own issue, but I noticed the test.robotmoose site is not up to date with the most recent commit. Presumably a merge conflict prevented the auto push.

**Comment by mrmoss** [comment]
I just did a manual update, no merge conflicts. @FineTralfazz which script does the auto update?

**Comment by FineTralfazz** [comment]
I just did some tests and it appears to be working currently. Let me know if it happens again.
