### ISSUE TITLE
Backend and frontend Gruveo call names do not match

### ISSUE THREAD

**Issue by Arsh25** [robotmoose/robotmoose#144]
The back and frontend are creating different hashes for the call name. This was encountered on an updated repo.

**Comment by mrmoss** [comment]
Are you using the same auth code? Are you using the first pilot to connect?

**Comment by Arsh25** [comment]
There was only 1 pilot and both sides where using an empty auth code. piloting worked so with code was correct.

**Comment by mrmoss** [comment]
Just because the auth input on the backend is empty it doesn't mean the
auth is empty (it's cleared when you hit connect). As I recall, the auth
code is saved as well. Was it using a previous auth code?

**Comment by Arsh25** [comment]
No auth was previously used. I don't believe if we save the auth code, if we do and it shows an empty auth field then that should be filed as a bug.

**Comment by mrmoss** [comment]
I can't reproduce this (unless I use a pilot that is not the first pilot)...so I just removed the single pilot based video altogether...

**Comment by Arsh25** [comment]
What do you mean by first pilot? The first pilot to ever connect to the robot or the first pilot amongst the current list of pilots? If it's the latter than we just had one pilot while testing but there were older pilots who were no longer connected and did not show up on superstar too

**Comment by mrmoss** [comment]
The pilot with the lowest uuid in the current list under frontend_status (the oldest pilot that is connected).

**Comment by mrmoss** [comment]
Was someone else connected? Right now, someone other than me is connected to stealth_layla, so I had to find a robot with no other pilots to test with...

**Comment by Arsh25** [comment]
Ok. So we had it not work when there was only one pilot connected

**Comment by Arsh25** [comment]
Nope, the backend reported only 1 pilot connected when we had the issue

**Comment by mrmoss** [comment]
Weird...I tried for a good 20 minutes to reproduce this. Did you have an old version of the backend?

**Comment by Arsh25** [comment]
No, I pulled the repo before using the backend

**Comment by mrmoss** [comment]
Did you check your app version?

**Comment by olawlor** [comment]
If you open a new backend and connect to a LAYLA with an auth code, the backend's gruveo link is wrong until you disconnect and reconnect.  This is with 2016-10-25 roadkill backend, and the production robotmoose.com frontend.

**Comment by mrmoss** [comment]
Alright, I think it's working. I removed the whole auth clearing bit of
code (changes the input box...thus why the recall was commented out in the
onchange event).

It looks like production apps have the inspector restricted, so you cannot
just "look" at an auth code with right-click+inspect...
