### ISSUE TITLE
HTTPS introduces substantial delay

### ISSUE THREAD

**Issue by raikaDial** [robotmoose/robotmoose#147]
Using http with the Kinect, data posts to superstar just fine and few packets are lost. Using https, many packets are lost, substantially reducing the kinect data update rate.

**Comment by Arsh25** [comment]
Are you using KEEP-ALIVE? I can totally see the lag being introduced due to each update having to do the TLS handshake.

**Comment by mrmoss** [comment]
It is not krep alive (single request via mongoose). Mongoose does have the
option, but this would be a major refactor to wget.hpp/wget.cpp.

**Comment by raikaDial** [comment]
We should use keepalive if we ever expect a superstar client to need to use https on a regular basis. But with the way superstar is setup now, everything posted to it is publicly viewable anyway, so clients should not be posting sensitive information.

**Comment by Arsh25** [comment]
Yeah I agree we aren't really posting any sensitive information. The only problem with using HTTP is the possibility of a replay attack but honesty there's not much harm that can be done apart from posting bad data to superstar

**Comment by Arsh25** [comment]
I think we should use keep-alive anyways because that could help minimize the latency (though there is no way to tell without experimentation) but that is a big change and should  be discussed and/or its own issue

**Comment by mrmoss** [comment]
This isn't https, at home all kinect data is bad for me (this is latency period, https just happens to be enough on campus to cause the error, but http causes the error at home as well).
