### ISSUE TITLE
Frontend should remember last robot used.

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#15]
Maybe in a cookie or localstorage?

**Comment by Arsh25** [comment]
I think auth should not be stored

**Comment by FineTralfazz** [comment]
If someone already has access to your computer, you have more important things to worry about than them moving a robot around.

**Comment by Arsh25** [comment]
In schools students may switch computers between classes, so they should not be able to drive a robot just because the auth is stored.
