### ISSUE TITLE
Pilot should be able to play sounds

### ISSUE THREAD

**Issue by Arsh25** [robotmoose/robotmoose#17]
Pilot should be able to play sounds to get people's attention. This came up in the group activity

**Comment by Arsh25** [comment]
I found a bug with sending the sound list to superstar and it's not updating after the first robot. Reopening this as a bug.

**Comment by mrmoss** [comment]
I did some modding to this module (it was throwing errors and not getting the newest robot, didn't work with auth). Needs to be re-tested.
