### ISSUE TITLE
Chrome App leaks sockets (sometimes)

### ISSUE THREAD

**Issue by olawlor** [robotmoose/robotmoose#22]
The backend can enter a state where Chrome just says "Waiting for socket" when connecting to robotmoose, probably due to leaked sockets (in "getnext"?).

This was observed after 15 minutes on a Windows 10 box, with several disconnects/reconnects.

**Comment by FineTralfazz** [comment]
I've been looking into this today. I think I found where the problem is, I just need to decide how to fix it.
