### ISSUE TITLE
Chrome Backend App should be able to play music

### ISSUE THREAD

**Issue by olawlor** [robotmoose/robotmoose#25]
It'd be nice to give kids the ability to play simple (preselected) sounds and music on the robot.

E.g., a "honk" to get people's attention.

**Comment by FineTralfazz** [comment]
Duplicate of #17?

**Comment by olawlor** [comment]
Yes, this is a dupe!

**Comment by Arsh25** [comment]
Dupe of #17 which was closed via 4d6db05

**Comment by mrmoss** [comment]
I was going through and assigning closed issues to those that completed them...so there are probably more assignments I gave you... But this way we can see who did what.
