### ISSUE TITLE
Utility to copy robots

### ISSUE THREAD

**Issue by Arsh25** [robotmoose/robotmoose#31]
Script or utility to create new robots from already existing robots. Ideally, the user will be able to specify what they want copied.

Eg: Make new KT's from a demo KT and copy over only the config or the config and example code.

**Comment by computations** [comment]
Can't the expand_db tool be used for this, or am I not understanding the problem?

**Comment by Arsh25** [comment]
The expand_db tool could be used for this, But the idea behind this is to not have to expand the whole db to copy stuff over and then repackage it. This tool would use GET requests and superstar cgi params to copy stuff from one robot to another or maybe even multiple robots.

**Comment by Arsh25** [comment]
Reopening to add 
- <strike>Ability to recursively go through directories </strike>
- <strike>Copy to multiple robots</strike>
