### ISSUE TITLE
backend icon 

### ISSUE THREAD

**Issue by mfrancisco1** [robotmoose/robotmoose#56]
- help to define differences among software / parts one idea is to redraw RobotMoose icon to something like this for the backend:
  ![moose-backend](https://cloud.githubusercontent.com/assets/13486105/16065971/4f00e36c-327d-11e6-933b-f44ea2c1ee00.gif)
  This example is hacked together and assuming whoever did the original artwork can update it fairly easily 

M

**Comment by Arsh25** [comment]
Umm, that's a good idea but the kids will start making unwanted connections. :P

**Comment by atupek** [comment]
omg, that is too funny

**Comment by mfrancisco1** [comment]
kids will be kids, especially with South Park as style guide

**Comment by Arsh25** [comment]
Unanimous decision to use the icon

**Comment by mrmoss** [comment]
Done.
