### ISSUE TITLE
adjust values of ui elements during realtime

### ISSUE THREAD

**Issue by mfrancisco1** [robotmoose/robotmoose#57]
I want to adjust the speed of the roomba while it runs the bumpfollow routine (see "realtime bumperfollow" code in 2016/uaf/roomba4) but UI is disabled while in another state.  

in this code I used delay as sanity check.  Note that the button has a different behavior than the slider when using the delay to access them in the loop.  With a delay I can quickly click the slider to change value with a delay of about 20.  The button will not work even with the delay.

**Comment by Arsh25** [comment]
Button not working with a delay is a known bug and we are working on it. See issue #29. 

We pushed an update that clears the UI on a state change  (see #21)so the old UI not showing while in another state is working as intended. This was done to prevent clutter on the ui window.
