### ISSUE TITLE
build.robotmoose.com subdomain

### ISSUE THREAD

**Issue by FineTralfazz** [robotmoose/robotmoose#79]
For the automated build/testing project I'm working on, I need to be able to receive GitHub webhooks, which, because of the university firewall, means that I need to be listening on ports 80/443, which means that I need to create an Apache vhost, which is a lot cleaner if it uses a subdomain, so somebody adding a CNAME record for build.robotmoose.com would be nice. 

I don't know who controls our DNS records, but I'm guessing it's either @olawlor or @mrmoss.

**Comment by Arsh25** [comment]
Dr Lawlor handles the DNS records. If you prefer a non standard port, we can get that opened from OIT.  @FineTralfazz  I would email him.

**Comment by olawlor** [comment]
OK, build.robotmoose.com is now a CNAME for the main server.
