### ISSUE TITLE
add text entry ui element

### ISSUE THREAD

**Issue by mfrancisco1** [robotmoose/robotmoose#80]
for users to enter precise values in control panel / ui

**Comment by mrmoss** [comment]
So like a spinner?
http://www.html5tutorial.info/html5-number.php

**Comment by mfrancisco1** [comment]
yes, that would be great!

**Comment by Michaeasmith** [comment]
I just pushed this to the dev site. I called the function "spinner", but I feel like there is probably a more intuitive name for it. Any suggestions? Current usage:

spinner() - create spinner (returns value of spinner)
spinner("string") - creates spinner with label "string"
spinner("string", "store.x") - ties variable store.x to the value of the spinner

**Comment by mrmoss** [comment]
Looks good to me.
