### ISSUE TITLE
Robotmoose server  switvhed over to Nginx

### ISSUE THREAD

**Issue by Arsh25** [robotmoose/robotmoose#86]
The robotmoose server suddenly started running Nginx and stopped apache at 5:15 PM today (June 26). No one was on the server as far as @mrmoss and I could tell. We are monitoring the server.

@FineTralfazz : Anything you changed that could do this?

**Comment by mrmoss** [comment]
I just disabled the service from auto-starting:
sudo update-rc.d nginx disable

Logs just show nginix starting at 17:07:56. Apache doesn't have anything in
error.log or access.log, other than the absence of connectivity...

**Comment by FineTralfazz** [comment]
I installed nginx back when we were having the problems with Apache, but I haven't done anything today. It looks like the server rebooted today and nginx started first.

I went ahead and removed nginx since we're not using it. Does anyone know why the server rebooted?

**Comment by mrmoss** [comment]
It was weird. We were testing on the production site, it went down for
about 30 seconds or so until we noticed it. We forced reloaded the page,
nginix showed up.

**Comment by Arsh25** [comment]
I'm gonna called this solved if logs show a reboot. Since nginx is disabled
this shouldn't happen again

**Comment by FineTralfazz** [comment]
Weird. I guess I'll go ahead and close this, since it shouldn't happen again. Hopefully we don't start having random reboot problems.
