### ISSUE TITLE
Possibility to load and save a file locally.

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#9]
Teachers expressed interest in being able to load and save a file from the local machine.

**Comment by mrmoss** [comment]
Should we make this to where it loads/saves all states at once instead of one state at a time?

**Comment by Arsh25** [comment]
Yes we should, I found the download each state separately weird.

**Comment by FineTralfazz** [comment]
That was my initial plan, but I had such a hard time working with the state table code that I ended up doing them separately.

**Comment by mrmoss** [comment]
There should be a .get_states() accessor and a .active_state variable, that
makes the saving easy.

Loading is a little trickier, but take a look at this .rebuild_dropdown_m() function.

**Comment by mrmoss** [comment]
I just pushed some code that mostly does what we want here. There's a few things we need to decide here though:
- If a bad file is loaded, how do we want to handle files that aren't a json array (probably an error popup or an error notification on the modal...but the code to get us started is there).
- How should we handle loading? Should it overwrite the current program? Should it load it up as a new experiment with the filename's name? Should it have an input for the new experiment name (my preference)?

Please note that the loading from a file right now overwrites code that is there...probably not what we want...

**Comment by FineTralfazz** [comment]
Having an input for the experiment name seems like the best option.

**Comment by mrmoss** [comment]
Maybe a checkbox that overrides the input if the experiment name already exists? This way if you want to overwrite it you can?

The modal_createnew_t class (and the creation of it in state_table_t) pretty much has all the code the check if a state already exists. Maybe follow it's lead and go from there?

**Comment by FineTralfazz** [comment]
I just pushed a commit to do that. Test server auto-deployment is working now, so it's already live there. Let me know if it's what you had in mind.

**Comment by mrmoss** [comment]
Looks good to me.
