### ISSUE TITLE
Chat doesn't work with authentication

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#93]
Chat uses superstar_generic, which doesn't have built in authentication... If we could store chat as JSON, this would be trivial to add to the multiple get and set...

**Comment by Arsh25** [comment]
Self assigned since I have the other chat issue assigned to me

**Comment by mrmoss** [comment]
It might be worth changing the whole append/trim system to storing things as a JSON array. This would make this and adding the dates in #13 trivial.

**Comment by Arsh25** [comment]
Opened new issue for changing the append/trim system. See #94
